//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zooshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class composition_of_purchase
    {
        public int buy_id { get; set; }
        public int goods_id { get; set; }
        public int count { get; set; }
        public Nullable<int> pet_id { get; set; }
    
        public virtual goods goods { get; set; }
        public virtual pet pet { get; set; }
        public virtual purchase purchase { get; set; }
    }
}
